### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by frattomatti** [ludeeus/custom-component-store#19]
Every installation fail with "500 Internal Server Error"

Custom component store installed with hassbian-config on hassbian installation

**Comment by ludeeus** [comment]
What does the log say?

**Comment by frattomatti** [comment]
no logs are output, a blank page appears with the words: 
```
500 Internal Server Error
Server got itself in trouble
```
at the page:  http://###.###.#.##:8120/component/feedparser/install

where I find the correct log?

**Comment by ludeeus** [comment]
Depends on how you installed it, if you used docker it will be the container log

**Comment by frattomatti** [comment]
i have installed with hassbian-config automatic script, later i try to install on docker

**Comment by ludeeus** [comment]
I see then it will be in the service log, I'll make a PR to remove it from there later.

I will depreciate and archive this repo later today, you should check out HACS which does the same and more! :)
https://github.com/custom-components/hacs

**Comment by frattomatti** [comment]
okay thanks you, i'll try hacs :)
